server:
  port: 8080
  error:
    include-stacktrace: never # para que no se muestre el error largo

eas:
  jwt:
    security:
      enabled: true # si lo pongo en false no sera necesaria la autenticacion por token
    timezone: "America/Bogota"
    issuer: "www.estefa.net"
    token:
      auth:
        path: "/demo/oauth/cliente_credential/accesstoken"
      secret: "${APP_SECRET_KEY}" #variable de entorno
      expired-in: 60 #seconds

spring:
  datasource:
    driver-class-name: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    url: "jdbc:sqlserver://springsecurity-server.database.windows.net:1433;encrypt=true;trustServerCertificate=false;loginTimeout=30;database=prueba;"
    username: "${APP_USERNAME_DB}"
    password: "${APP_PASSWORD_DB}"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.SQLServerDialect"
    hibernate:
      dll-auto: "validate"