server:
  port: 8585
  error:
    include-stacktrace: never # para que no se muestre el error largo

eas:
  jwt:
    security:
      enabled: true
    timezone: "America/Bogota"
    issuer: "www.estefa.net"
    token:
      auth:
        path: "/demo/oauth/cliente_credential/accesstoken"
      secret: "hola este esta es mi clave secreta jeje"
      expired-in: 3600 #seconds
    excluded:
      path: "/demo/multi,/demo/otraexclusion" #ejemplos